# Federated Linear Regression

In [1]:
import pandas as pd
import numpy as np

In [2]:
from flr import FLR

In [3]:
X = np.array([[1, 2], [2, 2], [1, 3], [3, 2], [2, 3], [3, 1]])
Y = np.array([2, 2, 3, 3, 4, 2])

In [4]:
flr = FLR().fit(X, Y)

In [5]:
flr.predict(X)

array([1.81818182, 2.45454545, 3.09090909, 3.09090909, 3.72727273,
       1.81818182])

In [6]:
flr.merge(flr.copy())

In [7]:
flr.predict(X)

array([1.81818182, 2.45454545, 3.09090909, 3.09090909, 3.72727273,
       1.81818182])

In [8]:
X2 = np.array([[0, 1], [2, 2], [1, 3], [3, 3]])
Y2 = np.array([1, 2, 3, 4])

In [9]:
flr.merge(FLR().fit(X2, Y2))

In [10]:
flr.predict(X)

array([1.88863636, 2.44090909, 3.09318182, 2.99318182, 3.64545455,
       1.78863636])